### ISSUE TITLE
issue about dense_flow for opencv2 and opencv3

### ISSUE THREAD

**Issue by gss-ucas** [yjxiong/temporal-segment-networks#152]
Hi, @yjxiong
Before I use your dense flow project, I had opencv3.1, so I didn't build a local installation of opencv2 and build dense flow with opencv3.1. Then I use following command to extract optical flow, however I can't get wonderful result as paper.

`./build/extract_gpu -f=test.avi -x=tmp/flow_x -y=tmp/flow_y -i=tmp/image -b=20 -t=1 -d=0 -s=1 -o=dir -w=340 -h=256
`

Then I follow your guide to build a local installation of opencv2 and dense flow, and use the same command to extract optical flow.
However, same command, different opencv version, get different optical flow. I don't know why, maybe because they should have different parameter setting?
Could you give me some suggestion? I'm looking forward to your reply.

**Comment by yjxiong** [comment]
The OpenCV3.1 branch is contributed by users. I have not run heavy tests on it. But I think it may be due to the difference in interfacing with the OpenCV facilities. It is also possible that the output has some differences between versions, which could be dealt with by training and testing with the same version's output.

**Comment by gss-ucas** [comment]
Thanks for your reply. I will research it if I have time.
