### ISSUE TITLE
Error in testing rgb model

### ISSUE THREAD

**Issue by SXYJerry** [yjxiong/temporal-segment-networks#168]
Hi,xiong! When I run the code 'python tools/eval_net.py' , I got a problem and I have no idea to deal with it. I followed your work step by step.
Here is the error: Error parsing text-format caffe.NetParameter: 19:12: Message type "caffe.LayerParameter" has no field named "bn_param". Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/ucf101/tsn_bn_inception_rgb_deploy.prototxt
I'll be appreciate if you can help me to solve the problem.

**Comment by fetorres** [comment]
Hello,  you may have another version of caffe installed on the machine you are using, and the code may be finding that before it finds the temporal segment networks build of caffe in the lib/ directory.  If that is so, adjusting your paths to find the right caffe may solve the problem.

Rather than changing our user profiles to always find the temporal segment networks caffe version, we make sure the path is correct by adding the following lines to pyActionRecog/action_caffe.py:

sys.path.insert(0,'/data/torres/temporal-segment-networks/lib/caffe-action/python')
# Test to make sure we are using the Temporal Segment Networks caffe build:
assert caffe.__path__[0].split('/')[-3] == 'caffe-action'

More specifically, the top of my code now says:
import sys
sys.path.insert(0,'/data/torres/temporal-segment-networks/lib/caffe-action/python')

import caffe
# Test to make sure we are using the Temporal Segment Networks caffe build:
assert caffe.__path__[0].split('/')[-3] == 'caffe-action'
from caffe.io import oversample
import numpy as np
from utils.io import flow_stack_oversample, fast_list2arr
import cv2


Best,
Frank

**Comment by SXYJerry** [comment]
Thanks, Frank! I'm glad to receive your prompt reply, it helps me a lot. 
Best wishes with you!
Sincerely,
Jerry

**Comment by yjxiong** [comment]
@fetorres Thanks for the clarification.

Closing this. Please feel free to reopen it if you meet any further problem.
