### ISSUE TITLE
Question about the parameters

### ISSUE THREAD

**Issue by adwardlee** [yjxiong/temporal-segment-networks#52]
Hi @yjxiong @wanglimin ,
Congrats to you excellent work.
Did you only extract only 1 RGB frame and 5 stacked optical flow frames in one snippet? Since I notice that the new_length of RGB is 1 and the new_length of optical flow is 5. Morerover, why did you choose the test size 950 instead of the whole number of testing set? Can your caffe framework run with multi-GPUs of different types (e.g one TITANX and one GTX1080)? Thanks.

Best,
-L

**Comment by yjxiong** [comment]
Thanks for your interest in our works.

1. During training, for each segment, we randomly sample 1 snippet. Each snippet is composed of either 1 RGB frame or 5 continuous optical flow frames. More details can be found in the paper.

2. The test size needs to be multiplied by the number of GPUs, i.e. 4. That is around 3800, roughly the size of UCF test splits. However, the final performance is reported with the testing scripts instead of Caffe's on-the-fly validation.

3. It is OK to use multiple types of GPUs, (of course, no AMD ones). However, we suggest using a same type of GPUs to achieve maximal training speed.

**Comment by adwardlee** [comment]
Hi @yjxiong,

I misunderstand it. Thank you for your quick and detailed reply!

Best,
-L
