### ISSUE TITLE
about code guide "batch_size*iter_size*n_gpu, to be 128" 

### ISSUE THREAD

**Issue by zhujiagang** [yjxiong/temporal-segment-networks#76]
In your code file "/temporal-segment-networks/models/ucf101/tsn_bn_inception_flow_solver.prototxt" and "/temporal-segment-networks/models/ucf101/tsn_bn_inception_flow_train_val.prototxt". `batch_size: 32, iter_size: 1, n_gpu: 4.` But I think it is `batch_size*iter_size = 32` that matters to get the same peformance of your reference model instead of `batch_size*iter_size*n_gpu = 128`. Because different `n_gpu` is only different in memory capacity and spent training time and has nothing to do with the results of forward and gradient update. Do I understand right? 
I now use one Titan GPU  and I set `batch_size: 4 iter_size: 8 ` to be the same with your `batch_size*iter_size = 32`. But My rgb model and flow model training on UCF101 Split1 have lower performance than yours, about 1% and 2% lower than yours respectively. I don't know how to train exactly. But I found your solver file is different from what you write in your paper.

**Comment by yjxiong** [comment]
No. Number of GPU in effective Batchsize matters because it affects how many samples the network sees during the whole training process.

If you happen to read the README carefully, I have clearly stated the reason for the difference between parameters in the paper and the solver files here.

Closing this issue as this is not a potential bug or problem of code.
